#!/bin/sh

set -e

if [ "x$1" = xremove ]; then
	update-alternatives \
		--remove default.plymouth /usr/share/plymouth/themes/long-logo/long-logo.plymouth

        update-alternatives \
		--remove text.plymouth /usr/share/plymouth/themes/long-text/long-text.plymouth
fi

#DEBHELPER#
